[build]
  publish = "."

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[template.environment]
  NETLIFY_IDENTITY_REDIRECT_URL = "https://rapido-guinee.netlify.app/admin/"
